/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GbboPublic": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SupabaseCert": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
