name: Production Deploy

# Trigger the workflow manually
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to deploy (e.g., 1.0.0)"
        required: true

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: prod-deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  SST_STAGE: production

jobs:
  ProdDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_tag }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::599520864657:role/GithubActionsRunnerForGbboMain
          aws-region: us-east-1

      - name: Update Secrets
        env:
          SUPABASE_CERT: ${{ secrets.PROD_SUPABASE_CERT }}
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          echo $SUPABASE_CERT | npx sst secret set SupabaseCert
          echo $DATABASE_URL | npx sst secret set DatabaseUrl

      - name: Deploy app
        env:
          SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
        run: |
          npx sst deploy

      - name: Migrate DB
        run: |
          npm run migrate
